services:
  client:
    build:
      context: ./client
      args:
        VITE_MAPBOX_TOKEN: ${VITE_MAPBOX_TOKEN}
    image: crib-client:latest
    container_name: crib-client-prod
    ports:
      - "3000:3000"
    restart: unless-stopped
