DATA_DIR := "./data"
RAW_DATA := DATA_DIR / "01_raw"
PRIMARY_DATA := DATA_DIR / "03_primary"

bioregions-to-json:
    gdal vector reproject -d epsg:4326 -f GeoJSON {{RAW_DATA}}/marine_administrative_boundaries.gpkg {{PRIMARY_DATA}}/bioregions.json


pmtiles:
    tippecanoe --force -zg -o {{PRIMARY_DATA}}/mpas.pmtiles \
        -L '{"file": "{{PRIMARY_DATA}}/mpas_indexed.json", "layer":"mpas"}' \
        -L '{"file": "{{PRIMARY_DATA}}/bioregions.json", "layer":"bioregions"}'


fill-nodata input output distance="1":
    #!/usr/bin/env bash
    set -euo pipefail

    bands=$(gdalinfo {{input}} | grep -c '^Band ')
    tmp_files=()

    for ((b=1; b<=bands; b++)); do
        tmp="/tmp/b${b}.tif"
        gdal raster fill-nodata -b $b --max-distance {{distance}} {{input}} "$tmp" --overwrite
        tmp_files+=("$tmp")
    done

    gdal raster stack ${tmp_files[@]} {{output}} --overwrite
    rm "${tmp_files[@]}"
