DATA_DIR := "./data"
RAW_DATA := DATA_DIR / "01_raw"
PRIMARY_DATA := DATA_DIR / "03_primary"


mpas_pmtiles:
    gdal vector reproject -d epsg:4326 -f GeoJSON {{RAW_DATA}}/marine_conservation_areas_merged.gpkg /vsistdout/ | tippecanoe --force -z10 -o {{PRIMARY_DATA}}/mpas.pmtiles

fill-nodata input output distance="1":
    #!/usr/bin/env bash
    set -euo pipefail

    bands=$(gdalinfo {{input}} | grep -c '^Band ')
    tmp_files=()

    for ((b=1; b<=bands; b++)); do
        tmp="/tmp/b${b}.tif"
        gdal raster fill-nodata -b $b --max-distance {{distance}} {{input}} "$tmp"
        tmp_files+=("$tmp")
    done

    gdal raster stack ${tmp_files[@]} {{output}}
    rm "${tmp_files[@]}"
